{{- if and .Values.persistence.enabled (eq .Values.config.database.type "sqlite") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wimp.cpFullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wimp.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
