apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wimp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wimp.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ required "config.jwtSecret is required" .Values.config.jwtSecret | quote }}
  bootstrap-token: {{ required "config.bootstrapToken is required" .Values.config.bootstrapToken | quote }}
  admin-email: {{ .Values.config.defaultAdminEmail | quote }}
  admin-password: {{ .Values.config.defaultAdminPassword | quote }}
  db-password: {{ .Values.config.database.password | quote }}
