prometheus:
  prometheusSpec:
    scrapeInterval: 1m
    additionalScrapeConfigs:
      - job_name: "windows_exporter"
        scrape_interval: 30s
        http_sd_configs:
          - url: https://wimp.suei.io/prometheus/targets
            refresh_interval: 60s
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
