prometheus:
  prometheusSpec:
    scrapeInterval: 1m
    additionalScrapeConfigs:
      - job_name: "windows_exporter"
        scrape_interval: 30s
        http_sd_configs:
          - url: http://172.30.19.131:30000/prometheus/targets
            refresh_interval: 60s
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance

alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ["alertname", "instance"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      receiver: telegram
    receivers:
      - name: "null"
      - name: telegram
        telegram_configs:
          - bot_token: "8714366412:AAHbiQ56xy623UimVI2jBv5byIAthGYD63Q"
            chat_id: -5446201979
            parse_mode: HTML
            message: |
              ‼️ <b>{{ .GroupLabels.alertname }}</b>
              {{ range .Alerts }}
              <b>Instance:</b> {{ .Labels.instance }}
              <b>Summary:</b> {{ .Annotations.summary }}
              {{ end }}
